### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by RaymondArias** [futuresimple/helm-secrets#100]
I am wondering if this project's maintainers are actively developing this project, last commit was a few months ago and there are issues that need to be resolved.

If they are not then someone should fork this project and continue development.

@szibis or @mhyllander if either could let us know whether you guys are still working in this project that would be helpful

**Comment by mhyllander** [comment]
Hi, I agree that there is little progress in this project, which is too bad because it's a very useful plugin. I'm not a maintainer, I've only contributed one PR. For the moment it's fulfilling my needs, but I see that there are several PRs waiting with bug fixes and improvements.

**Comment by mhyllander** [comment]
After my PR was merged, @szibis said he was going to do some changes before releasing version 2.0.0. I think he is working on that in #70.

**Comment by farrellit** [comment]
I think if it takes months to make changes, this project either needs additional maintainers or the community needs to fork it.

**Comment by skang0601** [comment]
@szibis Are you interested in additional maintainers or passing on this project? I see several PRs hanging that I'd like to get merged in honestly.

**Comment by farrellit** [comment]
> If they are not then someone should fork this project and continue development.

I'm sure @szibis is at least as busy as the rest of us.  This repo is featured in the helm upstream, and it has lots of value.  It has to be able to grow along with the fast moving helm ecosystem.  

I'd like to see if folks here have interest in a community operated organization to own this project.  That way it's not tied to anyone's personal participation.  I don't see any testing of this, so maybe that's something we could improve for quicker PR acceptance.  If we end up somewhere happy, we can petition helm docs to update to our fork.  I think it's important that we demonstrate at least the quality of the existing repo.  

[I've already created the org](https://github.com/helm-secrets) and am sending invites to all contributors, but this discussion is very much still open.

**Comment by sstarcher** [comment]
@szibis Could you possibly add some additional maintainers to this repo so we can keep it alive without needing to fork it?

**Comment by szibis** [comment]
I am back. Open to talk and we will have more people to work on this project and plans. I was out-of-focus but now we need to move project forward with full focus.

**Comment by szibis** [comment]
@sstarcher Yes I am open to new maintainers and we will have time for this project in our team.

**Comment by sstarcher** [comment]
@szibis great to hear.  I'm wondering what your overall goal is for helm secrets.  Would you be interested in adding additional provider support like vault or is the goal to keep this simple and focused on sops.

**Comment by Just-Insane** [comment]
Support for a secrets backend like [Hashicorp Vault](https://www.vaultproject.io/) would be greatly appreciated.

It would also be nice to see examples of using helm-secrets with Helm's stable charts in the documentation.

**Comment by szibis** [comment]
Yes. Hashicorp Vault is something we like to consider in the project. 

First, we need to clean issues and merge PR's with a defined roadmap. 

Add more maintainers and focus on the current state of helm-secrets with 2.0 release that needs to be added to all projects that use helm-secrets like helmfile.

**Comment by Just-Insane** [comment]
> Yes. Hashicorp Vault is something we like to consider in the project.
> 
> First, we need to clean issues and merge PR's with a defined roadmap.
> 
> Add more maintainers and focus on the current state of helm-secrets with 2.0 release that needs to be added to all projects that use helm-secrets like helmfile.

Do you have any thoughts on how we want to impliment Vault support? Looks like there is an open issue on SOPS to add Vault as an alternate KMS service (https://github.com/mozilla/sops/issues/291).

Alternativly, we could use Vault as a KV store, which would be similar to how Ansible's [Hashi_Vault](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/hashi_vault.py) works.

I think the prefered option would be the second option, to have it pull values from the KV Store, as adding it as another KMS resource does not give us flexability in storing data.

**Comment by brianupskill** [comment]
I think that a discussion on Vault should happen in another thread.

**Comment by jkroepke** [comment]
I did it (create a own fork): https://github.com/jkroepke/helm-secrets/

If you still interest in vault support let me know here: https://github.com/jkroepke/helm-secrets/

**Comment by sstarcher** [comment]
@jkroepke creating a fork does not seem to be a great idea.  This project is still being maintained and it would be helpful if you would help them maintain it vs forking the project as @szibis is open to additional maintainers.

**Comment by jkroepke** [comment]
> still being maintained 

It doesn't feel like this.

**Comment by sstarcher** [comment]
Last commit 7 days ago.  Have you reached out to @szibis asking to be a maintainer?

**Comment by jkroepke** [comment]
@sstarcher  

As I understand @szibis isn't a member of this repo anymore. His status on the Comment left is "Contributor" not "Member" or "Owner".

@zendesk has the maintenance now.

**Comment by sstarcher** [comment]
Great, now let's give them some time to respond before we start abandoning ship.

**Comment by jkroepke** [comment]
@sstarcher 3 weeks ago. Until now, just an other copyright update.

How long we want to wait?

**Comment by sstarcher** [comment]
Looks like they are not responding.  @szibis are you going to add collaborators for this or should we consider it a dead project?

**Comment by jkroepke** [comment]
For me it's for a dead project now.
