### ISSUE TITLE
Is this maintained any longer?

### ISSUE THREAD

**Issue by sstarcher** [futuresimple/helm-secrets#109]
Should we consider this no longer maintained?

@farrellit Have you tried contacting the author I noticed you forked this repo.

**Comment by farrellit** [comment]
I did, sadly @szibis is apparently not available for maintaining this repo at this time.  

see https://github.com/futuresimple/helm-secrets/issues/100

**Comment by sstarcher** [comment]
@farrellit perfect thank you I did not see that one.
