### ISSUE TITLE
Validation failure on helm secrets install/upgrade

### ISSUE THREAD

**Issue by rudolphjacksonm** [futuresimple/helm-secrets#116]
I hope that I'm doing something wrong here as I cannot install my charts using `helm secrets install`. I've gone through the following steps:

1. Install helm secrets plugin: `helm plugin install https://github.com/futuresimple/helm-secrets`
2. Updated my helm repo with a `.sops.yaml` file including the thumbprint of my PGP key:
```
creation_rules: 
  - pgp: <thumbprint>
```
3. Verified that I can encrypt, decrypt, view and edit a `secrets.yaml file` stored in the `templates/` directory of my helm repo:

_Contents of secrets.yaml:_
```
apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: opaque
# placeholder values which are encrypted and stored in helm-environments
stringData:
    username: username
    password: password
```
_Encryption_
```
helm secrets enc templates/secrets.yaml
```
_Decryption_
```
helm secrets dec templates/secrets.yaml 
Decrypting templates/secrets.yaml
```

4. Verified that I can run `helm secrets template .` from within the directory of my helm project (the same directory where `.sops.yaml` is) and that it can process all of the charts. Interestingly, when it templates the secrets.yaml file it does not decrypt it and instead shows the file as encrypted in stdout. This is probably expected behavior but I wasn't sure.

After this, if I run `helm secrets install . -n foo` my chart fails to install with the following error:
```
Error: validation failed: unable to recognize "": no matches for kind "ENC[AES256_GCM,data:LaCDz2bs,iv:QAF2eot5oXxoPQFRrIIGrG4nye7EW53EsDFW928q35Q=,tag:Vv8rvTDqQx/YpCAfRoEHfA==,type:str]" in version "ENC[AES256_GCM,data:+90=,iv:d+4NNxNPw5M3Xw7XMUCtoBIZdzPacxNflA59vQMgLR8=,tag:B/yVmBNv5wBTcBHB10wYiQ==,type:str]"
Error: plugin "secrets" exited with error
```

I thought the plugin would decrypt the encrypted secrets.yaml file and send it to Tiller when running helm secrets install/upgrade, but it doesn't seem to be working. If I'm doing something wrong or I've missed something obvious please let me know!

EDIT:
I've also tried the following, which has even stranger behavior.
1. Moved `secrets.yaml` to another directory outside of my helm chart
2. Passed the file as an argument, so the full command is now `helm secrets install . -f ../helm-environments/dev/secrets.yaml`

This successfully applies my chart but the secret is never created. I'm assuming this is because `secrets.yaml` is a secret and not a Values file, yet the docs show this example working:
```
helm secrets upgrade \
  helloworld \
  stable/java-app \
  --install \
  --timeout 600 \
  --wait \
  --kube-context=sandbox \
  --namespace=projectx \
  --set global.app_version=bff8fc4 \
  -f helm_vars/projectx/sandbox/us-east-1/java-app/helloworld/secrets.yaml \
  -f helm_vars/projectx/sandbox/us-east-1/java-app/helloworld/values.yaml \
  -f helm_vars/secrets.yaml \
  -f helm_vars/values.yaml
```

**Comment by mhyllander** [comment]
The only files that are decrypted are the ones passed to the "helm secrets install" or "helm secrets upgrade" using the -f or --values options. Those files are helm values files, and are used as input to helm when it renders the contents of the chart templates directory. (The files in the templates directory are templated kubernetes resources, not helm values files.)

So, when you have secret values, you would move them from values.yaml to secrets.yaml, and then encrypt secrets.yaml using "helm secrets enc secrets.yaml". Then you can pass the encrypted file as an argument "helm secrets install -n myrelease ./mychart -f mychart/secrets.yaml". The helm secrets plugin will decrypt secrets.yaml before passing it as input to "helm install". When "helm install" runs, it will see the decrypted values, use them to render the templates, and send the result to Tiller.

**Comment by orange-ly** [comment]
> The helm secrets plugin will decrypt secrets.yaml before passing it as input to "helm install"

Hi @mhyllander i'm using 3.0.0 and the `helm secret install` don't decrypt the encrypted secrets.yaml before send it to `helm install`

are you aware of the error?
Thank you
Joao

**Comment by orange-ly** [comment]
> 2\. Passed the file as an argument, so the full command is now `helm secrets install . -f ../helm-environments/dev/secrets.yaml`

hi @rudolphjacksonm did you reference your secret in some file under your /templates folder?
