### ISSUE TITLE
Helm plugin install specific version

### ISSUE THREAD

**Issue by Jdavid7x** [futuresimple/helm-secrets#122]
Hi, 

When i try to install a specific version of helm secrets is getting an error. 

  * Helm Version: 2.14.0

```
helm plugin install https://github.com/futuresimple/helm-secrets --version=2.0.1
Error: requested version "2.0.1" does not exist for plugin "https://github.com/futuresimple/helm-secrets"
```
The version 2.0.1 appears on plugin.yaml in my localmachine. But when i go to the releases in your project the last one is 1.3.1

Can you review why is not posible to install the version 2.0.1 from the 'helm plugin install' command?

**Comment by willejs** [comment]
The repo needs a release cut and the commits tagged...
dup of this https://github.com/futuresimple/helm-secrets/issues/96

**Comment by szibis** [comment]
Released https://github.com/futuresimple/helm-secrets/releases/tag/v2.0.2

**Comment by Jdavid7x** [comment]
Thanks
