### ISSUE TITLE
issue following the example on OSX 

### ISSUE THREAD

**Issue by rawlingsj** [futuresimple/helm-secrets#21]
I've read the great blog https://lab.getbase.com/helm-secrets-a-missing-piece-in-kubernetes and am trying the example out but I'm running into a problem.  It's probably down to me but figured I'd raise an issue to check.

I've run:
```
helm plugin install https://github.com/futuresimple/helm-secrets
```
I've also cloned this repo and try to run the first usage example https://github.com/futuresimple/helm-secrets#usage-examples
```
helm secrets dec example/helm_vars/projectX/sandbox/us-east-1/java-app/secrets.yaml
Decrypting example/helm_vars/projectX/sandbox/us-east-1/java-app/secrets.yaml
[PGP]	 WARN[0000] Decryption failed                             fingerprint=4434EA5D05F10F59D0DF7399AF1D073646ED4927
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  4434EA5D05F10F59D0DF7399AF1D073646ED4927: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /Users/jr/.gnupg/secring.gpg: no such file or
      | directory; GPG binary error: exit status 2

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
Error: plugin "secrets" exited with error
```
I have a new osx machine so I figured I need to create a gpg key (is that right?)
```
brew install gpg
```
Now generated a new key:
```
gpg --gen-key
```
This created a file `~/.gnupg/pubring.kbx` but no `~/.gnupg/secring.gpg` which the error message above was looking for.  I came across this https://superuser.com/questions/1037401/pubring-gpg-and-secring-gpg-are-missing-after-key-generation which may be related.

I'm wondering if I've fallen down a wrong path or if this is a valid issue.  

Any ideas or thoughts?

**Comment by rawlingsj** [comment]
I managed to avoid the error message above by running 
```
gpg --export-secret-keys >~/.gnupg/secring.gpg
```
Though I still have an error which I'm guessing is I've missed a step setting up a master key 
```
Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```
I'll close this issue and do a bit more reading to understand what I'm supposed to be doing.

**Comment by haj** [comment]
Resetting the terminal and running the following command made the gpg-agent ask me for the master password again and it resolved the issue for me. 
```
reset
GPG_TTY=$(tty)
export GPG_TTY
```

**Comment by tsaylorAMG** [comment]
> ```
> gpg --export-secret-keys >~/.gnupg/secring.gpg
> ```

This fixed the issue for me. Thanks!
