### ISSUE TITLE
yaml error on a file that does not exist

### ISSUE THREAD

**Issue by roger-rainey** [futuresimple/helm-secrets#32]
I have been working on a file (secrets.yaml) which I had encrypted but it had some issues so I deleted the file, now when I try to run 

helm secrets enc secrets.yaml

it gives the following error:
Error unmarshalling file: Error unmarshaling input YAML: yaml: line 6: found unexpected ':'
Error: plugin "secrets" exited with error

The secrets.yaml file is no longer there, is it being cached somewhere?

-- I figured it out, had the template secrets.yaml in a subfolder and it was also drilling into the subfolder.

**Comment by szibis** [comment]
Looks like this is closed
