### ISSUE TITLE
Wrong SHA256 on install

### ISSUE THREAD

**Issue by gtaylor** [futuresimple/helm-secrets#6]
Running Ubuntu 16.04 with helm 2.4.2:
```
$ helm plugin install https://github.com/futuresimple/helm-secrets
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3909k  100 3909k    0     0  4078k      0 --:--:-- --:--:-- --:--:-- 4076k
Wrong SHA256

* Helm-secrets wrapper for helm binary: No /usr/local/bin/helm-wrapper installed
Installed plugin: secrets
```
The `Wrong SHA256` and failure to install helm-wrapper seem to leave me in a broken state.

**Comment by szibis** [comment]
i this is related to this https://github.com/kubernetes/helm/pull/2400

**Comment by szibis** [comment]
To fix this I suggest to ```helm plugin remove secrets``` and then remove ``` ~/.helm/cache/plugins/https-github.com-futuresimple-helm-secrets```

Install plugin from the beginning and all should work.

**Comment by szibis** [comment]
If you feel this is not solved or helping to solve this issue please reopen.
