### ISSUE TITLE
"getopt --test" failed in this environment.

### ISSUE THREAD

**Issue by kvokka** [futuresimple/helm-secrets#71]
ENV:
MacOS 10.14.
Helm 2.11

prepare:
```
$ helm plugin install https://github.com/futuresimple/helm-secret
$ brew install gnu-getopt
$ brew reinstall gnu-getopt # just for sure
```

issue:
```
$ helm secrets help
I’m sorry, "getopt --test" failed in this environment.

You may need to install enhanced getopt, e.g. on OSX using
"brew install gnu-getopt".
Error: plugin "secrets" exited with error
$ getopt --test && echo $?
0
```

I have no ideas what is going wrong, can you give me any idea?

Thank you!

**Comment by y9v** [comment]
I'm getting the same issue, and calling `getopt --test > /dev/null` yields no errors

**Comment by kvokka** [comment]
adding `export PATH="/usr/local/Cellar/gnu-getopt/1.1.6/bin":$PATH` to `~/.zshrc` resolved the problem.

**Comment by spuder** [comment]
For bash users

`echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile`
