### ISSUE TITLE
helm secrets dec not working and deleting secrets file

### ISSUE THREAD

**Issue by mzupan** [futuresimple/helm-secrets#88]
I have a simple setup just using pgp

.sops.yml
```
---
creation_rules:
  - pgp: B6EE067A65308CA16B0D39FE27FAE19092947959

```

I can run `enc` and `view` just fine

```
$ helm secrets enc ./secrets.yml
Encrypting ./secrets.yml
Encrypted secrets.yml
```

When I try to decrypt I'm getting the following

```
$ helm secrets dec ./secrets.yml
Decrypting ./secrets.yml
sops metadata not found
Error: plugin "secrets" exited with error
$ ls secrets.yml
ls: secrets.yml: No such file or directory
```

```
$ sops -v
sops 3.2.0 (latest)
```

**Comment by mzupan** [comment]
of course, I figure it out once I post this but the difftool was looking for yaml and mine was yml

```
secrets.yaml diff=sopsdiffer
secrets.*.yaml diff=sopsdiffer
```

**Comment by tintranvan** [comment]
Hi,
The files must be .yaml not .yml. You have to change the file name to *.yaml and try again.

**Comment by worldofprasanna** [comment]
But I feel it's a bit strange. My .gitattributes is
```
secrets.yml diff=sopsdiffer
secrets.*.yml diff=sopsdiffer
```
and if I try to view the secrets, its working fine
```
helm secrets view secrets.yml
# Giving proper result
```

whereas if I try to decrypt it, its failing with the `sops metadata not found` and the file is removed. But if I rename the file to .yaml, decryption is working fine.

Any reason why this behaviour for "yml" files and not "yaml" files.
