### ISSUE TITLE
MacOS/BSD xargs doesn't support -r

### ISSUE THREAD

**Issue by mdibaiee** [futuresimple/helm-secrets#90]
Hi,

The BSD `xargs` does not support `-r`, and as such, when using `helm secrets`, this issue arises:

```
>>>>>> Cleanup
/usr/bin/xargs: illegal option -- r
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
            [-L number] [-n number [-x]] [-P maxprocs] [-s size]
            [utility [argument ...]]
Error: plugin "secrets" exited with error
```

The usage of `xargs` is here: https://github.com/futuresimple/helm-secrets/blob/76b7f29c18a7f47885cb4a76392a2ed6b0086ec2/secrets.sh#L342

**Comment by szibis** [comment]
fixed by https://github.com/futuresimple/helm-secrets/pull/103
