### ISSUE TITLE
Create a version 2.0.0 tag?

### ISSUE THREAD

**Issue by gmorse81** [futuresimple/helm-secrets#96]
i would like to lock in the version of helm secrets i am using, but version 2 is not tagged. the only way to currently install version 2 is from master which could change at any time.

**Comment by astorath** [comment]
@szibis how about making a new (2.0.2) release on github now?

**Comment by madAndroid** [comment]
We'd also like to be able to pin to a release newer than `1.3.1`, any chance you can create a new `2.x.x` release now? :)

**Comment by willejs** [comment]
I have emailed @mateuszzawisza about this and hit @szibis up on keybase. Hopefully we can get a release...

**Comment by szibis** [comment]
Sorry for long response - released https://github.com/futuresimple/helm-secrets/releases/tag/v2.0.2
